//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronos.Client.Win.DotNet.BasicProfiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chronos.Client.Win.DotNet.BasicProfiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppDomains.
        /// </summary>
        internal static string AppDomainsMenuItem_Text {
            get {
                return ResourceManager.GetString("AppDomainsMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies.
        /// </summary>
        internal static string AssembliesMenuItem_Text {
            get {
                return ResourceManager.GetString("AssembliesMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        internal static string ClassesMenuItem_Text {
            get {
                return ResourceManager.GetString("ClassesMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code View.
        /// </summary>
        internal static string CodeViewMenuItem_Text {
            get {
                return ResourceManager.GetString("CodeViewMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        internal static string FunctionsMenuItem_Text {
            get {
                return ResourceManager.GetString("FunctionsMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Menu&gt;
        ///  &lt;Control Id=&quot;Chronos.Client.Win.Menu.DotNet.DotNetMenuItem&quot;&gt;
        ///    &lt;Control Type=&quot;Chronos.Client.Win.Menu.DotNet.BasicProfiler.AppDomainsMenuItem, Chronos.Client.Win.DotNet.BasicProfiler&quot; /&gt;
        ///    &lt;Control Type=&quot;Chronos.Client.Win.Menu.DotNet.BasicProfiler.AssembliesMenuItem, Chronos.Client.Win.DotNet.BasicProfiler&quot; /&gt;
        ///    &lt;Control Type=&quot;Chronos.Client.Win.Menu.DotNet.BasicProfiler.ModulesMenuItem, Chronos.Client.Win.DotNet.BasicProfiler&quot; /&gt;
        ///    &lt;Control Ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string ModulesMenuItem_Text {
            get {
                return ResourceManager.GetString("ModulesMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.NET Base.
        /// </summary>
        internal static string ProfilingTypeDisplayName {
            get {
                return ResourceManager.GetString("ProfilingTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads.
        /// </summary>
        internal static string ThreadsMenuItem_Text {
            get {
                return ResourceManager.GetString("ThreadsMenuItem_Text", resourceCulture);
            }
        }
    }
}
