//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronos.Client.Win.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chronos.Client.Win.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Profiling.
        /// </summary>
        public static string Profiler_Configurations_AvailableConfigurationsView_Title {
            get {
                return ResourceManager.GetString("Profiler_Configurations_AvailableConfigurationsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Configurations.
        /// </summary>
        public static string Profiler_Configurations_RecentConfigurationsView_Title {
            get {
                return ResourceManager.GetString("Profiler_Configurations_RecentConfigurationsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Profiler_Groups_HomeView_Title {
            get {
                return ResourceManager.GetString("Profiler_Groups_HomeView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronos .NET Profiler.
        /// </summary>
        public static string Profiler_MainView_Title {
            get {
                return ResourceManager.GetString("Profiler_MainView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Assembly.
        /// </summary>
        public static string Profiler_Options_AddAssemblyView_Title {
            get {
                return ResourceManager.GetString("Profiler_Options_AddAssemblyView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Profiler.
        /// </summary>
        public static string Profiler_Options_InstallationView_InstallProfilerButton_Content {
            get {
                return ResourceManager.GetString("Profiler_Options_InstallationView_InstallProfilerButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Profiler_Options_InstallationView_Title {
            get {
                return ResourceManager.GetString("Profiler_Options_InstallationView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Profiler.
        /// </summary>
        public static string Profiler_Options_InstallationView_UninstallProfilerButton_Content {
            get {
                return ResourceManager.GetString("Profiler_Options_InstallationView_UninstallProfilerButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories:.
        /// </summary>
        public static string Profiler_Options_PerformanceCountersView_CategoriesTextBlock_Text {
            get {
                return ResourceManager.GetString("Profiler_Options_PerformanceCountersView_CategoriesTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counters:.
        /// </summary>
        public static string Profiler_Options_PerformanceCountersView_CountersTextBlock_Text {
            get {
                return ResourceManager.GetString("Profiler_Options_PerformanceCountersView_CountersTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Categories.
        /// </summary>
        public static string Profiler_Options_PerformanceCountersView_LoadPerformanceCategoriesButton_Content {
            get {
                return ResourceManager.GetString("Profiler_Options_PerformanceCountersView_LoadPerformanceCategoriesButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Counters:.
        /// </summary>
        public static string Profiler_Options_PerformanceCountersView_TargetCountersTextBlock_Text {
            get {
                return ResourceManager.GetString("Profiler_Options_PerformanceCountersView_TargetCountersTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Counters.
        /// </summary>
        public static string Profiler_Options_PerformanceCountersView_Title {
            get {
                return ResourceManager.GetString("Profiler_Options_PerformanceCountersView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Profiler_Options_ProfilingEventsView_Title {
            get {
                return ResourceManager.GetString("Profiler_Options_ProfilingEventsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiling Filter.
        /// </summary>
        public static string Profiler_Options_ProfilingFilterView_Title {
            get {
                return ResourceManager.GetString("Profiler_Options_ProfilingFilterView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically open process view when profiling is started.
        /// </summary>
        public static string Profiler_Options_ShellView_OpenProcessWhenProfilingStartedCheckBox_Content {
            get {
                return ResourceManager.GetString("Profiler_Options_ShellView_OpenProcessWhenProfilingStartedCheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell.
        /// </summary>
        public static string Profiler_Options_ShellView_Title {
            get {
                return ResourceManager.GetString("Profiler_Options_ShellView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Profiler_OptionsView_Title {
            get {
                return ResourceManager.GetString("Profiler_OptionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations.
        /// </summary>
        public static string Profiler_Pages_ConfigurationsPageView_Title {
            get {
                return ResourceManager.GetString("Profiler_Pages_ConfigurationsPageView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Profiler_Pages_SessionsPageView_Title {
            get {
                return ResourceManager.GetString("Profiler_Pages_SessionsPageView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiling Data.
        /// </summary>
        public static string Profiler_ProcessShadow_WinApplicationView_Title {
            get {
                return ResourceManager.GetString("Profiler_ProcessShadow_WinApplicationView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly References.
        /// </summary>
        public static string Profiler_References_AssemblyView_Title {
            get {
                return ResourceManager.GetString("Profiler_References_AssemblyView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class References.
        /// </summary>
        public static string Profiler_References_ClassView_Title {
            get {
                return ResourceManager.GetString("Profiler_References_ClassView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function References.
        /// </summary>
        public static string Profiler_References_FunctionView_Title {
            get {
                return ResourceManager.GetString("Profiler_References_FunctionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Sessions.
        /// </summary>
        public static string Profiler_Sessions_ActiveSessionsView_Title {
            get {
                return ResourceManager.GetString("Profiler_Sessions_ActiveSessionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Sessions.
        /// </summary>
        public static string Profiler_Sessions_SavedSessionsView_Title {
            get {
                return ResourceManager.GetString("Profiler_Sessions_SavedSessionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Profiler_Sessions_StartSessionView_CloseButton_Content {
            get {
                return ResourceManager.GetString("Profiler_Sessions_StartSessionView_CloseButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiling Filter:.
        /// </summary>
        public static string Profiler_Sessions_StartSessionView_FilterConfigurationTextBlock_Text {
            get {
                return ResourceManager.GetString("Profiler_Sessions_StartSessionView_FilterConfigurationTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Profiler_Sessions_StartSessionView_StartProfilingButton_Content {
            get {
                return ResourceManager.GetString("Profiler_Sessions_StartSessionView_StartProfilingButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Session.
        /// </summary>
        public static string Profiler_Sessions_StartSessionView_Title {
            get {
                return ResourceManager.GetString("Profiler_Sessions_StartSessionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Profiler_ThreadTraceView_ReloadTraceButton_Content {
            get {
                return ResourceManager.GetString("Profiler_ThreadTraceView_ReloadTraceButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Tree.
        /// </summary>
        public static string Profiler_ThreadTraceView_Title {
            get {
                return ResourceManager.GetString("Profiler_ThreadTraceView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppDomains.
        /// </summary>
        public static string Profiler_Unit_AppDomainsView_Title {
            get {
                return ResourceManager.GetString("Profiler_Unit_AppDomainsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies.
        /// </summary>
        public static string Profiler_Unit_AssembliesView_Title {
            get {
                return ResourceManager.GetString("Profiler_Unit_AssembliesView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callstacks.
        /// </summary>
        public static string Profiler_Unit_CallstacksView_Title {
            get {
                return ResourceManager.GetString("Profiler_Unit_CallstacksView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Profiler_Unit_ClassesView_Title {
            get {
                return ResourceManager.GetString("Profiler_Unit_ClassesView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions.
        /// </summary>
        public static string Profiler_Unit_ExceptionsView_Title {
            get {
                return ResourceManager.GetString("Profiler_Unit_ExceptionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string Profiler_Unit_FunctionsView_Title {
            get {
                return ResourceManager.GetString("Profiler_Unit_FunctionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Profiler_Unit_ModulesView_Title {
            get {
                return ResourceManager.GetString("Profiler_Unit_ModulesView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql Requests.
        /// </summary>
        public static string Profiler_Unit_SqlRequestsView_Title {
            get {
                return ResourceManager.GetString("Profiler_Unit_SqlRequestsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads.
        /// </summary>
        public static string Profiler_Unit_ThreadsView_Title {
            get {
                return ResourceManager.GetString("Profiler_Unit_ThreadsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronos.
        /// </summary>
        public static string Rhiannon_MessageBoxView_Title {
            get {
                return ResourceManager.GetString("Rhiannon_MessageBoxView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: .
        /// </summary>
        public static string UnitCollectionView_FilterTextBlock_Text {
            get {
                return ResourceManager.GetString("UnitCollectionView_FilterTextBlock_Text", resourceCulture);
            }
        }
    }
}
